import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <span>Home Page</span>
        &nbsp;&nbsp;&nbsp;
        <Link href="/ssr">
          <a>SSR Page</a>
        </Link>
        &nbsp;&nbsp;&nbsp;
        <Link href="/csr">
          <a>CSR Page</a>
        </Link>
      </nav>
    </div>
  );
};

export default Home;
